//! Generates this crate's view of the ABI from the published header.
//!
//! There is no hand-written declaration of the boundary anywhere in `src/`,
//! which is the whole point: a struct somebody typed out agrees with whatever
//! they believed the header said on the day they typed it, and a field that
//! moved afterwards does not fail to compile. It reads its neighbour's bytes.
//!
//! It also computes the fingerprint the same way the shim does, from the same
//! file, so the handshake at run time compares two numbers derived from two
//! copies of the header rather than a number against itself.
//!
//! No dependencies. A binding generator and a hash crate would both be
//! reasonable, and both would turn an offline conformance run into a network
//! test with a supply chain to audit. The parser below understands exactly the
//! subset of C this header is allowed to use, and refuses anything else rather
//! than guessing.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let header = match env::var("VIPRS_ACAD_HEADER") {
        Ok(p) => PathBuf::from(p),
        Err(_) => manifest
            .join("../../../include/viprs_acadsharp.h")
            .canonicalize()
            .expect("the published header is not where this crate expects it"),
    };

    println!("cargo:rerun-if-changed={}", header.display());
    println!("cargo:rerun-if-env-changed=VIPRS_ACAD_LIB_DIR");
    println!("cargo:rerun-if-env-changed=VIPRS_ACAD_HEADER");

    let bytes = fs::read(&header).expect("cannot read the header");
    let digest = sha256_hex(&bytes);
    let fingerprint = u64::from_str_radix(&digest[..16], 16).unwrap();

    let text = String::from_utf8(bytes).expect("the header is not UTF-8");
    let mut out = String::new();
    out.push_str("// Generated by build.rs from the published header. Do not edit.\n");
    out.push_str(&format!(
        "pub const VIPRS_ACAD_HEADER_SHA256: &str = \"{}\";\n",
        digest
    ));
    out.push_str(&format!(
        "pub const VIPRS_ACAD_EXPECTED_FINGERPRINT: u64 = 0x{:016X};\n\n",
        fingerprint
    ));
    out.push_str(&generate(&text));

    // The test-only export is not in the published header, and must not be:
    // it is compiled only into the shim's test configuration. So the
    // generator adds it when asked and the source tree still declares nothing
    // by hand.
    println!("cargo:rustc-check-cfg=cfg(viprs_test_exports)");
    println!("cargo:rerun-if-env-changed=VIPRS_ACAD_TEST_EXPORTS");
    if env::var("VIPRS_ACAD_TEST_EXPORTS").is_ok() {
        out.push_str("\nextern \"C\" {\n    pub fn viprs_acad__test_throw(kind: u32) -> u32;\n}\n");
        println!("cargo:rustc-cfg=viprs_test_exports");
    }

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("abi.rs");
    fs::write(&dest, out).expect("cannot write the generated bindings");

    if let Ok(dir) = env::var("VIPRS_ACAD_LIB_DIR") {
        println!("cargo:rustc-link-search=native={}", dir);
        println!("cargo:rustc-link-lib=dylib=viprs_acadsharp");
    } else {
        panic!("VIPRS_ACAD_LIB_DIR is not set, so there is no shim to link against");
    }
}

/// The header with block comments removed. Comments carry the reasons, and a
/// parser that read them would pick up a type name out of a sentence.
fn strip_block_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'*' {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                if bytes[i] == b'\n' {
                    out.push('\n');
                }
                i += 1;
            }
            i += 2;
            continue;
        }
        out.push(bytes[i] as char);
        i += 1;
    }
    out
}

fn generate(header: &str) -> String {
    let code = strip_block_comments(header);
    let mut out = String::new();
    let mut rest = String::new();

    // Constants, structs and opaque handles, line by line. Everything else
    // falls through to the prototype pass below.
    let mut in_struct: Option<(String, Vec<(String, String)>)> = None;
    for line in code.lines() {
        let t = line.trim();

        if let Some((_, fields)) = in_struct.as_mut() {
            if t == "};" {
                let (name, fields) = in_struct.take().unwrap();
                out.push_str("#[repr(C)]\n");
                out.push_str("#[derive(Debug, Clone, Copy, Default, PartialEq)]\n");
                out.push_str(&format!("pub struct {} {{\n", name));
                for (ty, field) in fields {
                    out.push_str(&format!("    pub {}: {},\n", field, ty));
                }
                out.push_str("}\n\n");
                continue;
            }
            if t.is_empty() {
                continue;
            }
            let parts: Vec<&str> = t.trim_end_matches(';').split_whitespace().collect();
            assert_eq!(
                parts.len(),
                2,
                "a struct member this generator does not understand: {:?}",
                t
            );
            fields.push((rust_scalar(parts[0]), parts[1].to_string()));
            continue;
        }

        if t.starts_with("#define ") {
            let parts: Vec<&str> = t["#define ".len()..].split_whitespace().collect();
            if parts.len() == 2 {
                let value = parts[1].trim_end_matches('u');
                if !value.is_empty() && value.chars().all(|c| c.is_ascii_digit()) {
                    out.push_str(&format!("pub const {}: u32 = {};\n", parts[0], value));
                }
            }
            continue;
        }

        if t.starts_with('#') {
            continue;
        }

        if t.starts_with("typedef struct ") && t.ends_with(';') {
            let name = t["typedef struct ".len()..]
                .trim_end_matches(';')
                .split_whitespace()
                .next()
                .unwrap();
            out.push_str("#[repr(C)]\n");
            out.push_str(&format!(
                "pub struct {} {{\n    _opaque: [u8; 0],\n}}\n\n",
                name
            ));
            continue;
        }

        if t.starts_with("struct ") && t.ends_with('{') {
            let name = t["struct ".len()..].trim_end_matches('{').trim().to_string();
            in_struct = Some((name, Vec::new()));
            continue;
        }

        if t.starts_with("extern ") || t == "}" {
            continue;
        }

        rest.push_str(line);
        rest.push('\n');
    }

    out.push('\n');
    out.push_str("extern \"C\" {\n");
    for chunk in rest.split(';') {
        let chunk = chunk.trim();
        if chunk.is_empty() || !chunk.contains('(') {
            continue;
        }
        out.push_str(&prototype(chunk));
    }
    out.push_str("}\n");
    out
}

fn prototype(chunk: &str) -> String {
    let open = chunk.find('(').unwrap();
    let close = chunk.rfind(')').unwrap();
    let head: Vec<&str> = chunk[..open].split_whitespace().collect();
    let name = head[head.len() - 1];
    let ret = head[..head.len() - 1].join(" ");

    let params = chunk[open + 1..close].trim();
    let mut rendered = Vec::new();
    if params != "void" && !params.is_empty() {
        for (i, p) in params.split(',').enumerate() {
            rendered.push(parameter(p, i));
        }
    }

    let returns = if ret == "void" {
        String::new()
    } else {
        format!(" -> {}", rust_scalar(&ret))
    };

    format!(
        "    pub fn {}({}){};\n",
        name,
        rendered.join(", "),
        returns
    )
}

fn parameter(raw: &str, index: usize) -> String {
    let stars = raw.matches('*').count();
    let is_const = raw.split_whitespace().any(|t| t == "const");
    let cleaned = raw.replace('*', " ");
    let tokens: Vec<&str> = cleaned
        .split_whitespace()
        .filter(|t| *t != "const" && *t != "struct")
        .collect();
    assert!(
        tokens.len() >= 2,
        "a parameter this generator does not understand: {:?}",
        raw
    );

    let name = tokens[tokens.len() - 1];
    let base = tokens[tokens.len() - 2];
    let mut ty = rust_scalar(base);
    for level in 0..stars {
        ty = if level == 0 && is_const {
            format!("*const {}", ty)
        } else {
            format!("*mut {}", ty)
        };
    }

    let name = if name == "type" || name == "fn" {
        format!("arg{}", index)
    } else {
        name.to_string()
    };
    format!("{}: {}", name, ty)
}

fn rust_scalar(c: &str) -> String {
    match c.trim() {
        "uint8_t" => "u8".into(),
        "uint16_t" => "u16".into(),
        "uint32_t" => "u32".into(),
        "uint64_t" => "u64".into(),
        "double" => "f64".into(),
        "void" => "core::ffi::c_void".into(),
        other => other.into(),
    }
}

// --------------------------------------------------------------------------
// sha256, so the fingerprint is derived here the same way the shim derives it.
// --------------------------------------------------------------------------

const K: [u32; 64] = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

fn sha256_hex(data: &[u8]) -> String {
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];

    let mut message = data.to_vec();
    let bit_len = (data.len() as u64) * 8;
    message.push(0x80);
    while message.len() % 64 != 56 {
        message.push(0);
    }
    message.extend_from_slice(&bit_len.to_be_bytes());

    for block in message.chunks(64) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([
                block[i * 4],
                block[i * 4 + 1],
                block[i * 4 + 2],
                block[i * 4 + 3],
            ]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }

        let (mut a, mut b, mut c, mut d) = (h[0], h[1], h[2], h[3]);
        let (mut e, mut f, mut g, mut hh) = (h[4], h[5], h[6], h[7]);

        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);

            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }

        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }

    h.iter().map(|word| format!("{:08x}", word)).collect()
}
